### PR TITLE
Issue/consistent object naming

### LINKED ISSUE #16: Consistent object and field naming
Opening this issue to discuss breaking changes around data model.
IMO it's important to set things straight before the project grows too much.

Here are my observations/recommendations:

## 1. Consistent wording

**Observation**
Project uses a mix of different terms/abbreviations/cases for object names, field names, tabs and other labels.

Some examples for field names:
- repository vs repo - Example: `GitHub_Repos__x.RepositoryURL__c` vs `GitHub_Repos__x.RepoCreatedDate__c`
- pull request vs pr - Example: `GitHub_Pull_Requests__x.PullRequestURL__c` vs `GitHub_Pull_Requests__x.PRUpdatedDate__c`
- URL vs url - Example: `GitHub_Repos__x.RepositoryURL__c` vs `GitHub_Repos__x.LanguagesUrl__c`

**Recommendation**
We should try to use the same wording everywhere for consistency.
How about:
- We use the long form for "top level info":
  - object names and labels
  - tab labels
  - report labels
  - component labels
- We use short form for "detailed info":
  - field API names and labels

## 2. Object API naming convention

**Observation**
External object API names are all using plural form (GitHub Repos, GitHub Issues...).

**Recommendation**
Object API names should all be singular to match Salesforce best practices.
That's why we have a "Plural Label" field in setup ;)

## 3. Field API naming convention

I'll leave that one as a bonus. I don't think that it's mandatory to implement this.

**Observation**
External field API names follow Pascal case (`ClosedDate__c`...)

**Recommendation**
Field API names should follow the Salesforce case (a mix of Pascal case and snake case like `Closed_Date__c`).
This case should be consistent with Object API name case.

### PR DESCRIPTION
**Pull request by KarlPatach**
Fixes #16

### CODE REVIEW

**Comment by KarlPatach** [comment]
Converted to draft as there are still a few setup issues (e.g. validating and syncing will create new objects instead of mapping to existing ones)

**Comment by pozil** [comment]
Ok, if you go down that path, it could be interesting to check if you can create relationships between the external objects:
Repo -> PR
Repo -> Issue

Disclaimer: I don't know what's required to achieve that. Perphaps it's for a dedicated PR...

**Comment by pozil** [comment]
Relationships would allow us to do proper reporting on multi-objects.

**Comment by KarlPatach** [comment]
I think this will be done in at least one other PR. Btw I will create a new issue for Issue-->user relationship that has been broken in a previous PR (syncing the external object reseted this setting)

**Comment by KarlPatach** [comment]
Sorry for the number of files @pozil 😅 Renaming one object meant modifying like 10 files at a time...

**Review by pozil — APPROVED** [review]
All good. Thanks for the changes.

**Pull request merged**
